import test from 'node:test';
import assert from 'node:assert/strict';
import { canonicalUrl, deadlineIsOpen, dispositionFor, evidenceIsInCandidate, extractJson, registerLead } from '../src/lib.js';
test('canonical URL removes tracking', () => assert.equal(canonicalUrl('HTTPS://Example.com/path/?utm_source=x&keep=y#section'), 'https://example.com/path?keep=y'));
test('expired lead is never delivered', () => { const lead = { sourceUrl: 'https://notice.test/a', buyer: 'Buyer', title: 'Live interpreter', spokenEvidence: 'simultaneous interpreting', languageEvidence: 'Arabic English', deadline: '2020-01-01' }; assert.equal(dispositionFor(lead, { leads: [] }, new Date('2026-08-08')).action, 'expired'); assert.equal(deadlineIsOpen('2020-01-01', new Date('2026-08-08')), false); });
test('same identity is suppressed after first delivery', () => { const lead = { sourceUrl: 'https://notice.test/a?utm_source=x', buyer: 'Buyer', title: 'Live interpreter', country: 'France', mode: 'VRI', spokenEvidence: 'video remote interpreting', languageEvidence: 'Arabic French', deadline: '2026-12-01', recurring: false }; const registry = { leads: [] }; const first = dispositionFor(lead, registry, new Date('2026-08-08')); registerLead(registry, lead, first, new Date('2026-08-08')); assert.equal(dispositionFor(lead, registry, new Date('2026-08-09')).action, 'duplicate'); });
test('recurring lead waits 30 days', () => { const lead = { sourceUrl: 'https://notice.test/roster', buyer: 'Buyer', title: 'Interpreter roster', country: 'UK', mode: 'OPI', spokenEvidence: 'telephone interpreting', languageEvidence: 'Arabic English', recurring: true }; const registry = { leads: [] }; registerLead(registry, lead, dispositionFor(lead, registry, new Date('2026-08-01')), new Date('2026-08-01')); assert.equal(dispositionFor(lead, registry, new Date('2026-08-15')).action, 'suppressed-recurring'); });
test('evidence quote must be in fetched direct content', () => { const candidate = { url: 'https://notice.test/a', text: 'The buyer requires simultaneous interpreting from Arabic into French for a live conference.' }; const valid = { sourceUrl: 'https://notice.test/a', spokenEvidence: 'simultaneous interpreting', languageEvidence: 'Arabic into French' }; assert.equal(evidenceIsInCandidate(valid, [candidate]), true); assert.equal(evidenceIsInCandidate({ ...valid, spokenEvidence: 'invented quote' }, [candidate]), false); });
test('JSON parser accepts fenced response', () => assert.deepEqual(extractJson('```json\n{"shortlist":[]}\n```'), { shortlist: [] }));
