import test from 'node:test';
import assert from 'node:assert/strict';
import { agnesDigest, exaSearch, openAiWebDigest } from '../src/providers.js';
function mockFetch(expectedUrl, expectedBody, reply) { return async (url, options) => { assert.equal(url, expectedUrl); const body = JSON.parse(options.body); expectedBody(body, options.headers); return new Response(JSON.stringify(reply), { status: 200, headers: { 'content-type': 'application/json' } }); }; }
test('Exa request uses deep direct-source search and blocks aggregators', async () => {
  const results = await exaSearch('Arabic interpreter roster', 'exa-key', { startPublishedDate: '2026-08-01T00:00:00.000Z', excludeDomains: ['aggregator.test'] }, mockFetch('https://api.exa.ai/search', (body, headers) => { assert.equal(headers.authorization, 'Bearer exa-key'); assert.equal(body.query, 'Arabic interpreter roster'); assert.equal(body.startPublishedDate, '2026-08-01T00:00:00.000Z'); assert.equal(body.type, 'deep'); assert.deepEqual(body.excludeDomains, ['aggregator.test']); assert.equal(body.contents.text.maxCharacters, 3500); }, { results: [{ url: 'https://buyer.test/notice', title: 'Notice', text: 'Direct notice', highlights: ['live interpreting'] }] }));
  assert.equal(results[0].url, 'https://buyer.test/notice');
});
test('Agnes request uses OpenAI-compatible chat completions', async () => { const result = await agnesDigest({ model: 'agnes-2.5-flash', apiKey: 'agnes-key', system: 'Strict JSON', prompt: 'Return JSON', fetchImpl: mockFetch('https://apihub.agnes-ai.com/v1/chat/completions', (body, headers) => { assert.equal(headers.authorization, 'Bearer agnes-key'); assert.equal(body.model, 'agnes-2.5-flash'); assert.equal(body.messages[0].role, 'system'); assert.equal(body.messages[1].content, 'Return JSON'); }, { choices: [{ message: { content: '{"shortlist":[]}' } }] }) }); assert.equal(result.text, '{"shortlist":[]}'); });
test('OpenAI Responses request enables hosted web search and collects cited URLs', async () => { const result = await openAiWebDigest({ model: 'gpt-5.6', apiKey: 'openai-key', prompt: 'Find notices', fetchImpl: mockFetch('https://api.openai.com/v1/responses', (body, headers) => { assert.equal(headers.authorization, 'Bearer openai-key'); assert.equal(body.tools[0].type, 'web_search'); assert.deepEqual(body.include, ['web_search_call.action.sources']); }, { output: [{ type: 'web_search_call', action: { sources: [{ url: 'https://buyer.test/notice' }] } }, { type: 'message', content: [{ type: 'output_text', text: '{"shortlist":[]}', annotations: [{ type: 'url_citation', url: 'https://buyer.test/notice' }] }] }] }) }); assert.equal(result.text, '{"shortlist":[]}'); assert.deepEqual(result.sourceUrls, ['https://buyer.test/notice']); });
